### ISSUE TITLE
I am interested in the project. When the code is available?

### ISSUE THREAD

**Issue by zxydi1992** [zhuchen03/ConvexPolytopePosioning#1]

**Comment by zhuchen03** [comment]
Thank you for your interest! We'll get it ready before June 8.

**Comment by zxydi1992** [comment]
> Thank you for your interest! We'll get it ready before June 8.

Btw, I'd like to implement some part of the Algorithm 1. I wonder how you check the convergence with the  two "while" statements. Plus, is it \| A^TA \|_2 = \sqrt{\sum_i, j c{i,j}^2}? (C=A^TA)

**Comment by zhuchen03** [comment]
Yes we are using | A^TA |_2 = \sqrt{\sum_i, j c{i,j}^2} in our implementation. The goal of setting step size to alpha=1/| A^TA |_2 is to make it smaller than 2/M so that the convex optimization problem is guaranteed to converge, where M is the Lipschitz constant of the gradient. In this problem, M should be equal to the l2 operator norm of A^TA, but the Frobenius is an upper bound of M and is easier to compute. 

For the inner while loop, we just need to observe whether the objective value changes less than a threshold after one update step. For the outer loop, usually we just set a fixed number of iterations enough for convergence.

**Comment by zxydi1992** [comment]
> Yes we are using | A^TA |_2 = \sqrt{\sum_i, j c{i,j}^2} in our implementation. The goal of setting step size to alpha=1/| A^TA |_2 is to make it smaller than 2/M so that the convex optimization problem is guaranteed to converge, where M is the Lipschitz constant of the gradient. In this problem, M should be equal to the l2 operator norm of A^TA, but the Frobenius is an upper bound of M and is easier to compute.
> 
> For the inner while loop, we just need to observe whether the objective value changes less than a threshold after one update step. For the outer loop, usually we just set a fixed number of iterations enough for convergence.

That helps a lot. Thanks.
